fourkie/fourkie

- src/_components/common-emotion-image.tsx
- src/_components/types/ImgComponent.type.ts
- src/app/(home)/components/home-diary.tsx
- ref #21 
<br>
> 이미지 컴포넌트를 작성했습니다.
> 피그마의 사이즈를 기준으로 수행했습니다.
> 사용방법은 해당 컴포넌트에 작성해두었습니다. 
> 작성된 사용방법 주석은 후에 리펙토링할 때 삭제하도록 하겠습니다!
<br>
위 xl 아래 xs
<br>
> [Feature/Component] 공통 이미지 컴포넌트 #21

- src/app/sign-in/_components/sign-in-form.tsx
- src/app/sign-up/_components/sign-up-form.tsx
- src/app/sign-up/type.ts
- src/constants/form-message.ts
- src/services/auth-services.ts
- #10
<br>
> 회원가입시 닉네임 추가 로직 구현
> supabase 에서 auth - public  연결되지 않는 오류 해결
<br>
<br>
> 혹시나 로그인이나 회원가입시에 이상이 생기면 말씀해주세요!
> [Feature/Mypage] 회원가입 시 닉네임 추가, supabase 테이블에 연동 #10

- src/services/auth-services.ts
- src/services/supabase-server.ts
- src/services/supabase.ts
Ref #10
<br>
> 로컬 스토리지에 추가되던 토큰이 쿠키로 이동하였습니다.
<br>
<br>
getSession()은 공식 홈페이지에서 왠만하면 사용하지 말라고 합니다.
getUser()를 강력 추천 한다네요! 
```
const { data: { user } } = await supabase.auth.getUser()
```
```
{
"data": {
"user": {
"id": "11111111-1111-1111-1111-111111111111",
"aud": "authenticated",
"role": "authenticated",
"email": "example@email.com",
"email_confirmed_at": "2024-01-01T00:00:00Z",
"phone": "",
"confirmed_at": "2024-01-01T00:00:00Z",
"last_sign_in_at": "2024-01-01T00:00:00Z",
"app_metadata": {
"provider": "email",
"providers": [
"email"
]
},
"user_metadata": {
"email": "example@email.com",
"email_verified": false,
"phone_verified": false,
"sub": "11111111-1111-1111-1111-111111111111"
},
"identities": [
{
"identity_id": "22222222-2222-2222-2222-222222222222",
"id": …
```
> [Refactor/SignUp,SignIn] supabase 로직 변경 #10

- database.types.ts
- package.json
> 4월 3일자 튜터님의 강의를 기반으로 supabase 타입을 만들었습니다. 
<br>
> [add] supabase type 추가

- src/types/common-components.types.ts
- src/ui/common/button.tsx
- #25 
<br>
> 버튼 컴포넌트
> Props로 내용 전달
###Props
- children: 안에 들어가는 텍스트
- disabled
- onClick
- icon: 버튼 안에 넣을 아이콘
- iconPosition: 아이콘 위치
<br>
아직 디자인은 적용하지 않았습니다. (와이어프레임 버튼 디자인이 통일되지 않음)
<br>
> 추가로 넣어야할 props가 있을까요?
> [Feature/component] 버튼 컴포넌트 추가

- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/list-card.tsx
- src/app/list/page.tsx
- src/hooks/queries/use-get-all-posts-query.ts
- src/hooks/queries/use-get-user-by-id-query.ts
- src/services/post-services.ts
- src/services/user-services.ts
- src/types/posts.types.ts
- #5 
<br>
> 카드 컴포넌트 추가
> 카드 컨테이너 컴포넌트 추가
> 정보 불러오기
> 오늘 작성된 글만 필터링
<br>
> [Feature/List] 컴포넌트 추가 #5

- src/_components/common-emotion-image.tsx
- src/app/(home)/components/home-diary.tsx
- src/app/(home)/components/home-nopost.tsx
- src/constants/toast-message.ts
- src/services/home-services.ts
ref #3 
<br>
- 현식님의 pr을 토대로 유저별로 데이터를 가져올 수 있게 수정했습니다.
- 유저의 게시물이 없을 시 추가를 유도했습니다.
- 로그인하지 않은 사용자는 list 쪽으로 이동하게 했습니다.
- 이미지 컴포넌트에 속성을 하나 추가했습니다. 
<br>
<br>
> 최대한 상수화를 시도했습니다!
> [Feature/Home] 홈페이지 기능 업데이트 #3

- src/app/(home)/components/home-date.tsx
- src/app/(home)/components/home-diary.tsx
- src/app/page.tsx
-ref #3 
<br>
- 데이터 피커를 반영해서 만들었습니다.
- 최대한 css에 맞게 이것저것 시도해봤습니다.
- 상단에 글을 바꿨습니다.
- 미래 (아직 지나지 않은 날짜)를 선택할 수 없습니다.
- 클릭 후 키보드로 값을 변경할 수 없습니다.
- 선택 부분에 커스텀 색을 적용했습니다.
<br>
<br>
> 라이브러리 너무 어려워요 ^__^... 머리털 다 뽑힌 것 같아
- 아래 명령어를 통해 라이브러리를 설치해주세요!
pnpm add @mui/x-date-pickers @mui/material @emotion/react @emotion/styled dayjs
> [Feature/Home] date picker 반영 #3

- package.json
- pnpm-lock.yaml
- src/app/api/spotify/callback/route.ts
- src/app/api/spotify/login/route.ts
- src/app/api/spotify/token/route.ts
- src/constants/spotify.ts
- src/constants/toast-message.ts
- #4
<br>
> Spotify OAuth 인증 플로우 구현 (Authorization Code → Access Token 발급)
> Access Token 만료 시 Refresh Token으로 재발급 로직 구현
> 인증 / 토큰 발급 과정에서 발생하는 에러에 대한 응답 및 에러 메시지 설정
> 관련 에러 메시지들을 상수 파일(TOAST_MESSAGE)로 정리하여 일관성 확보
> Spotify 관련 상수를 SPOTIFY 객체로 분리하여 유지보수성 향상
<br>
> /music 로 이동했을 경우
> http://localhost:3000/api/spotify/login 로 이동했을 경우
<br>
> toast-message.ts 파일에서 오류 내용에 대해 중복되거나 통일시켜야 하는 게 있다면 말해주세요 !!
> 파일 위치가 잘못됐다면, 혹은 변경을 원하시면 말해주세요 !!
> [Feature/Music] Spotify 인증 및 토큰 갱신 로직 구현 및 에러 메시지 정리 #4

- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/list-card.tsx
- src/app/list/page.tsx
- src/hooks/queries/use-get-all-posts-query.ts
- src/hooks/queries/use-get-friend-posts-query.ts
- src/hooks/queries/use-get-my-posts-query.ts
- src/services/friend-services.ts
- src/services/post-services.ts
- src/services/user-services.ts
- #5 
<br>
> 탭으로 친구 게시물/내 게시물 조건부 렌더링
> ** 다크모드로 되어있어서 클릭 시 글씨가 보이지 않는 점 ,,, 다음부턴 light 모드로 바꾸어 작업하거나 하겠습니다 흑 ㅜ
> 스크린샷의 첫번째가 내 게시물, 두번째가 친구 게시물입니다.
<br>
> [Feature/List] 친구 게시물 / 내 게시물 조건부 렌더링

- src/app/api/posting/route.ts
- src/app/posting/_components/posting-form.tsx
- src/app/posting/_components/posting-result-modal.tsx
- src/app/posting/page.tsx
- src/app/posting/type.ts
- src/hooks/mutations/use-post-emotion-mutation.ts
- src/services/posting-services.ts
Ref #8
<br>
- 모달에 띄울 코드와 form안에만 들어갈 코드를 분리하였습니다.
- 변수명을 바꿨습니다.
<br>
- 없음
<br>
> [Refactor/Posting] 파일 분리

- src/app/(layout)/navigation.tsx
- src/app/layout.tsx
- #42 
<br>
> 대표 페이지 라우팅
> 추후 시안 나오면 디자인 적용 하겠습니다
<br>
<br>
> [Feature/component] Navigation 기본 기능

- src/app/(home)/components/home-calendar.tsx
- src/app/(home)/components/home-date.tsx
- src/app/(home)/types/HomeDate.ts
- src/app/page.tsx
- src/constants/query-data.ts
- src/hooks/queries/use-get-user-posts-by-month-query.ts
ref #3 
<br>
- 달력과 데이트 피커를 연결했습니다.
- 달력의 css를 다듬었습니다.
- 데이트 피커의 css를 다듬었습니다.
- 유저 정보 불러오는 것에 텐스텍 쿼리를 적용하였습니다.
- 펜딩, 에러 처리했습니다.
- 이미지+숫자 >> 이미지만 나타내기
<br>
<br>
"month" 도 상수화로 표현하려했으나 함수안에 사용하니 오류가 발생하여 그냥 두었습니다.
> [Feature/Home] 달력과 데이트피커 연결 

- package.json
- pnpm-lock.yaml
- src/app/posting/_components/posting-form.tsx
- src/app/posting/_components/posting-result-modal.tsx
- src/app/posting/page.tsx
- src/app/posting/type.ts
- src/hooks/mutations/use-post-emotion-mutation.ts
- src/services/posting-services.ts
Ref #8 
<br>
- 로딩창 스타일 개선
- 로딩창에 닉네임 표시
- 비 로그인 사용자는 포스팅 페이지에 접근하려 하면 로그인 페이지로 보냄
- 변수명 수정
- lucide-react 다운로드
<br>
<br>
[로딩 창 개선.webm](https://github.com/user-attachments/assets/704a7f72-c787-4d0b-9112-a1ab523742bb)
> lucide-react를 다운받았습니다! pull 받으시면 pnpm install 해주세요!
> [Feature/posting] 감정 분석 로딩창 개선 및 닉네임 삽입 #8

- src/app/(home)/components/home-calendar.tsx
- src/app/(home)/components/home-date.tsx
- src/app/(home)/components/home-header.tsx
- src/app/page.tsx
- src/services/home-services.ts
REF #3 
<br>
- 홈에서 사용하는 헤더를 구현하였습니다.
- 앞선 피드백에 맞춰 주석과 콘솔을 조금 정리했습니다. 
- 닉네임 가져오는 코드를 작성했습니다
- 라우팅 처리를 수정했습니다.
<br>
<br>
색상은 이후에 pr 올라오면 한번에 적용하겠습니다!
> [Feature/Homeheader] 상단에 닉네임 헤더와 작성 버튼 추가 및 코드 리펙토링 #3

- src/app/(layout)/navigation.tsx
- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/list-card.tsx
- #5 
<br>
> 내 게시물 / 친구 게시물에 따라 보여지는 정보 다르게 하기
> 기본값으로 두줄만 노출 후 더보기 기능
<br>
https://github.com/user-attachments/assets/1c7fea11-38b3-4702-93aa-24118d3120c4
> [Feature/List] 카드 컴포넌트 구체화

- src/app/api/posting/route.ts
- src/app/posting/_components/posting-form.tsx
- src/app/posting/_components/posting-result-modal.tsx
- src/app/posting/page.tsx
- src/app/posting/type.ts
- src/services/posting-services.ts
Ref #8 
<br>
- 감정 분석 결과에 테스트 코드를 삽입하여 임시로 감정 결과가 나오게 함
- route.ts 파일 코드 개선
- 필요없는 await 코드 제거
<br>
<br>
[테스트 코드 감정 분석 결과.webm](https://github.com/user-attachments/assets/11a635a2-5333-45c4-9d00-39d1fc15af6a)
> 테스트 코드 moods를 삽입했습니다.
> [Feature/posting] 감정 분석 결과 모달창 기능 추가#8

- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/list-card.tsx
- src/app/page.tsx
- src/constants/emotion.constant.ts
- src/hooks/queries/use-get-my-posts-query.ts
- src/services/post-service.ts
- src/ui/common/emotion-graph.tsx
- src/ui/common/popup.tsx
- src/utils/emotion-graph-cal.util.ts
- #50 
<br>
> 최근 3개월 내 게시물의 감정 통계
> 팝업 작업
> [Feature/List] 감정 통계 로직

- src/app/api/spotify/callback/route.ts
- src/app/music/[id]/page.tsx
- src/app/music/_components/emotion-select.tsx
- src/app/music/_components/playlist-item.tsx
- src/app/music/_components/playlist-list.tsx
- src/app/music/_components/tab-buttons.tsx
- src/app/music/page.tsx
- src/app/music/type.ts
- src/constants/music-constant.ts
- src/constants/toast-message.constant.ts
- src/services/music-bookmark-service.ts
- src/services/music-service.ts
- #4
<br>
> Supabase 연동 및 유저 인증 처리
> 로그인된 유저의 북마크 데이터 조회 및 새로고침 시에도 상태 유지
> 플레이리스트에 북마크(즐겨찾기) 추가 / 삭제 기능 구현
> 총 곡 수 표기 및 Spotify 외부 링크 이동 기능 추가
> 타입 분리 및 정리
> UI 컴포넌트 분리 및 props 구조 정리
<br>
<br>
> 우선 급하게 기능 구현만 한 거라, 바로 리팩토링 진행할 예정입니다.
> 변수명, 파일 위치 등 다 임의로 설정한 것이니 많은 피드백 부탁드립니다.
> [Feature/m client] 감정 기반 추천 및 북마크 기능 구현 #4

- src/app/(home)/components/home-friend.tsx
- src/app/sign-up/_components/sign-up-form.tsx
- src/services/home-client-service.ts
- src/services/home-service.ts
REF #3 
<br>
회원가입 > 홈 헤더 설정 / 이름 리펙토링 / css 다듬기 
<br>
> [Feature/Homepage] 회원가입 > 홈 헤더 설정 / 이름 리펙토링 / css 다듬기 

- src/app/music/_components/bookmarked-playlists.tsx
- src/app/music/_components/playlist-card.tsx
- src/app/music/_components/playlist-tab-container.tsx
- src/app/music/page.tsx
- src/app/music/type.ts
- src/services/music-bookmark-service.ts
> [Feature/m client] 충돌 가득 뮤테이션.. #4

- src/app/list/_components/list-card.tsx
- src/app/music/_components/bookmarked-playlists.tsx
- src/app/music/_components/playlist-card.tsx
- src/app/music/_components/recommend-playlists.tsx
- src/app/music/page.tsx
- src/app/posting/_components/posting-emotion-modal-slice.tsx
- src/hooks/mutations/use-music-bookmarks-mutation.ts
- src/hooks/mutations/use-remove-post-mutation.ts
- src/services/post-service.ts
- src/ui/common/emotion-graph.tsx
> [Refactor] 북마크 관련 코드 정리 및 삭제 기능 개선

- src/app/(home)/components/home-calendar.tsx
- src/app/(home)/components/home-friend.tsx
- src/app/(home)/components/home-header.tsx
- src/app/(home)/components/home-music.tsx
- src/app/(layout)/navigation.tsx
- src/ui/common/emotion-image.common.tsx
REF #3 
REF #86 
<br>
- 홈- 달력 그림자 약하게(완) 
- 글씨 크기 base로 (완)
- 글씨 폰트 적용하기  > 피그마에 홈은 적용이 안되어있어서 놔둠
- 네비바 마이페이지 부분 조절하기 (완)
- 네비바 리스트 부분 아이콘 바꾸기 (완)
- 헤더에 뒤로가기 추가하기 (완)
- 헤더 글씨 줄이기(완)
- 헤더 : 닉네임 기록 16PX BOLD (완)
- 이미지 크기 하나 추가하기 (완)
<br>
<br>
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> [Feature/Homepage] 홈/ 네비/ 헤더 수정 #86  #3 

- src/app/posting/_components/posting-form.tsx
> [Style/Posting]: 게시글 폼의 텍스트 영역 스타일 및 레이아웃 개선

- src/app/list/_components/list-card.tsx
- src/ui/common/emotion-graph.tsx
- #5 
<br>
> ui 디테일 수정
> 감정 팝업 컴포넌트 마이페이지에서도 사용 가능하게 리팩토링
<br>
> [Feature/List] 그래프 팝업 ui/ 기능 업데이트

- src/app/music/_components/bookmarked-playlists.tsx
- src/app/music/_components/playlist-card.tsx
- src/app/music/_components/playlist-tab-container.tsx
- src/app/music/_components/recommend-playlists.tsx
- src/app/music/page.tsx
- src/app/music/type.ts
- src/constants/music-constant.ts
- src/constants/spotify.constant.ts
- src/constants/toast-message.constant.ts
- src/hooks/mutations/use-music-bookmarks-mutation.ts
- src/hooks/queries/use-get-all-bookmarked-playlists-by-id-query.ts
- src/hooks/queries/use-get-all-playlists-by-query-query.ts
- src/services/music-bookmark-service.ts
- #4
<br>
> 추천 플리 탭 : Spotify 요청
> 즐겨찾기 탭 : Supabase 요청
<br>
<br>
> MVP 기능 및 1차 발표 끝나고 리팩토링 진행하겠습니당
> 그래도 다들 수고 많으셨습니다 !!
> [Refactor/music] Music 페이지 기능 구현 완료

- src/app/sign-in/_components/sign-in-form.tsx
- src/app/sign-up/_components/sign-up-form.tsx
- src/types/components-props.type.ts
- src/ui/common/button.common.tsx
REF #3 
REF #86 
<br>
- 로그인 회원가입 부분 전체적인 css 작성
- 공통 버튼 컴포넌트 수정 
<br>
<br>
현식님 패턴 파이팅!!!!!
> [style/ sign-in,up] 기초 css #3

- src/app/layout.tsx
- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/list-card.tsx
- src/ui/common/emotion-graph.tsx
- tailwind.config.ts
- #5 
<br>
> tailwind.config 파일 수정
> [Feature/List] 팝업 css 수정

- src/app/list/_components/list-card.tsx
- #5 
<br>
> 수정/삭제 로직 제대로 작동하게 변경 (원래 둘이 뒤바뀌어 있었음)
> 띄어쓰기 없이 글이 이어질 시 줄바꿈 안되던 오류 해결 (
<br>
> [Feature/List] 줄바꿈, 삭제/수정 기능 제대로

- src/app/(home)/components/home-header.tsx
- src/app/(layout)/navigation.tsx
- src/app/layout.tsx
- src/app/page.tsx
- src/app/posting/_components/posting-form.tsx
REF #3 
Ref #86 
<br>
- 헤더 리펙토링
- 헤더 상단 고정
> [Feature/Home] 헤더 상단 고정 및 리펙토링 #3

- src/services/user-search-service.ts
- #7 
<br>
> 토스트 미친듯이 뜨던 에러 수정
> [Feature/List] 친구찾기 토스트 에러 수정

- pnpm-lock.yaml
- src/app/list/_components/list-card-container.tsx
- src/app/music/_components/bookmarked-playlists.tsx
- src/app/music/_components/emotion-select.tsx
- src/app/music/_components/playlist-card.tsx
- src/app/music/_components/playlist-tab-container.tsx
- src/app/music/_components/recommend-playlists.tsx
- src/app/music/page.tsx
- #4 
<br>
> 피그마 참고해서 UI 작업했습니다.
> 디테일 부분 빼고 거의 완성했습니다.
> 드롭다운 : shadCn 적용해서 해볼 예정인데,, 쉽지 않을 것 같습니다.
<br>
<br>
> 폰트 색상 : date-color 적용할 예정
> 앨범 이미지 : 라운드 조절 필요, 이미지 크기 설정
> 자세히 확인 후 피드백 부탁드립니다 !!
> [Design/music] Music 페이지 CSS 80% 완료 #4

- src/app/(home)/components/home-calendar.tsx
- src/app/list/_components/list-card-container.tsx
- src/app/page.tsx
- src/app/sign-in/_components/sign-in-form.tsx
- src/app/sign-up/_components/sign-up-form.tsx
- src/hooks/mutations/use-create-posts-mutation.ts
- src/hooks/queries/use-get-my-posts-query.ts
- src/ui/common/input.common.tsx
> [Featue/List] 전체 디테일 수정

- pnpm-lock.yaml
- src/app/list/_components/list-card.tsx
- src/app/my-page/components/mypage-graph.tsx
- src/app/my-page/components/mypage-menu-list.tsx
- src/app/posting/page.tsx
- src/app/sign-in/_components/sign-in-form.tsx
- src/app/sign-in/page.tsx
- src/app/sign-up/_components/sign-up-form.tsx
- src/app/sign-up/page.tsx
- src/constants/toast-message.constant.ts
- src/hooks/mutations/auth-mutation.ts
- src/services/auth-service.ts
- src/services/friend-request-service.ts
- src/services/supabase-server-service.ts
- src/ui/common/input.common.tsx
- src/ui/common/mypage-emotion-graph.tsx
Ref #10
<br>
- 로그인 시 로그인, 회원가입 페이지 접근 금지
- 로그인, 회원가입 시 에러 메세지 추가
- 로그인, 회원가입 페이지 스타일 수정
- 로그인, 회원가입 시 예외처리 추가
> [Feature/Sign] 로그인, 회원가입 페이지 #10

- .vscode/settings.json
- src/app/posting/_components/posting-form.tsx
- src/constants/query-keys.constant.ts
- src/hooks/queries/use-get-posts-by-postId-query.ts
- src/services/post-service.ts
Ref #8
<br>
- 포스팅 작성 및 수정 할때 대한민국 기준 시간으로 저장
- 포스팅 인풋창 포커스 했을 때 안내 문구 안 보이게 수정
<br>
<br>
[포커스 수정.webm](https://github.com/user-attachments/assets/9d4f9d39-22ab-467f-a1ce-1c75a2fe221f)
> [Feature/Posting] 포스팅 포커스 수정

- src/app/(layout)/navigation.tsx
- src/app/layout.tsx
- src/app/posting/page.tsx
- src/constants/query-keys.constant.ts
- src/constants/toast-message.constant.ts
- src/hooks/mutations/use-create-posts-mutation.ts
- src/hooks/mutations/use-remove-post-mutation.ts
- src/hooks/queries/use-get-posts-by-userId-and-today-query.ts
- src/services/post-service.ts
closed #8
<br>
- 레이아웃의 네비게이션 컴포넌트 위치 변경
- 하루 한번 포스팅 제한 설정
<br>
<br>
>
> 스타일의 변경은 없습니다!
> [Feature/Posting] 오늘 이미 포스팅된 경우, 추가 포스팅 제한 #8

- src/app/(home)/components/home-music.tsx
- src/app/notice/page.tsx
- src/app/terms/page.tsx
- src/hooks/mutations/use-create-posts-mutation.ts
- src/hooks/mutations/use-remove-post-mutation.ts
- src/hooks/mutations/use-update-posts-by-postId-mutation.ts
- src/hooks/queries/use-get-user-posts-by-month-query.ts
REF #107 
<br>
- 공지사항, 약관 정책 작업 
- 예외처리 잘못해서 홈에 오류나던 것 수정
- 홈에 뮤테이션 각각 다 연결
<br>
> [Refactor/homepage] 공지, 약관 페이지 제작/ 홈 오류 수정 / 홈 뮤테이션 수정 #107

- src/app/layout.tsx
- src/app/list/_components/list-card-container.tsx
- src/hooks/mutations/use-update-posts-by-postId-mutation.ts
- #108 
<br>
> 헤더 아래로 리스트가 가려지는 현상 해결
<br>
> [Feature/List] css 스타일 변경

- src/app/music/_components/bookmarked-playlists.tsx
- src/app/music/_components/emotion-select.tsx
- src/app/music/_components/playlist-card.tsx
- src/app/music/_components/playlist-tab-container.tsx
- src/app/music/_components/recommend-playlists.tsx
- src/app/music/_components/tab-button.tsx
- src/app/music/page.tsx
- src/app/music/type.ts
- src/constants/spotify.constant.ts
- src/constants/toast-message.constant.ts
- src/hooks/mutations/use-music-bookmarks-mutation.ts
- src/services/music-bookmark-service.ts
- #106
<br>
> 전체 UI 작업
> 일기 미작성 : 추천 플리 및 일기 작성 유도 메세지 보여주기
> 일기 작성 : post_emotion 받아서 유저 기본 감정 설정하기
<br>
<br>
> 홈페이지 음악 컴포넌트 랜덤 추천 부분은 다시 한 번 상의해봐야 할 것 같습니다.
> 추후 리팩토링 진행 예정입니다.
> [Refactor/music] 일기 작성 여부에 따른 플리 추천 기능 및 UI 수정 #106

- src/app/api/spotify/sign-out/route.ts
- src/constants/spotify.constant.ts
- src/services/auth-service.ts
- #106 
<br>
> `api/spotify/sign-out/route.ts` 파일 생성 및 POST 요청으로 인한 Spotify 쿠키 제거
<br>
> 로그아웃 시도 후, 확인 부탁드립니다.
> [Refactor/music] Spotify 로그아웃 기능 추가 및 상수 정리 #106

- src/app/friends/components/friend-request-button.tsx
- src/app/friends/page.tsx
- src/app/music/page.tsx
- src/hooks/queries/use-get-all-playlists-by-query-query.ts
- src/services/music-service.ts
> [Refactor] 음악 가져오는 기능 수정 및 디테일 수정

- src/app/(home)/components/home-header.tsx
- src/app/(layout)/navigation.tsx
- src/app/layout.tsx
- src/app/list/_components/list-card-container.tsx
- src/app/music/_components/emotion-select.tsx
- src/app/music/page.tsx
- src/app/my-page/components/mypage-menu-list.tsx
- src/app/smookie-makers/page.tsx
- src/app/terms/page.tsx
> [Refactor] 음악 레이아웃

- .vscode/settings.json
- src/app/(home)/components/home-header.tsx
- src/app/globals.css
- src/app/layout.tsx
- src/app/list/_components/list-card.tsx
- src/app/posting/_components/posting-form.tsx
- tailwind.config.ts
posting 페이지의 '게시' 버튼 헤더에 추가하였습니다.
> [Refactor] 게시 버튼 반응형으로 변경

- src/app/tutorial/_components/tutorial-description.tsx
> [Refactor/Tutorial] 컴포넌트의 여백 및 오버플로우 스타일 수정 #125

- src/app/tutorial/_components/tutorial-description.tsx
- tailwind.config.ts
ref #125
<br>
- 튜토리얼 페이지 스타일 수정
> [Refactor/Tutorial] 튜토리얼 List 설명 페이지 수정 #125

- src/app/(home)/components/home-music.tsx
- src/app/music/_components/playlist-card.tsx
style: 홈 음악 및 재생 목록 카드 컴포넌트의 이미지 크기 및 여백 조정
> style: 홈 음악 및 재생 목록 카드 컴포넌트의 이미지 크기 및 여백 조정 #106

- src/app/(home)/components/home-friend.tsx
> style: 코드 포맷팅 및 스타일 수정

- src/app/posting/_components/posting-form.tsx
close #138 
<br>
- 수정 버튼 누를 시 텍스트가 2줄만 불러와 지는 버그를 수정했습니다.
- 주석을 추가했습니다.
<br>
<br>
[수정 페이지 2줄만 불러와지는 버그 수정.webm](https://github.com/user-attachments/assets/dde600c2-4a36-4344-9a12-a94cc7ed213b)
>
> 곧 이 컴포넌트 리팩토링 할 예정입니다.
> [Bugfix/Posting] 수정할때 content가 잘못 불러와지는 버그 수정 #138

- src/app/list/_components/list-card-container.tsx
- src/constants/alert-message.ts
- src/ui/common/alert.tsx
> 알림창 디자인입니다.
> props로 title, contents 필수이고,
> children으로 필요한 버튼 사용하시면 됩니다. (공통 컴포넌트 버튼)
<br>
> [Feature] 공통 컴포넌트, 알림창

- src/app/sign-in/_components/sign-in-form.tsx
- src/app/sign-up/_components/sign-up-form.tsx
- src/app/tutorial/_components/tutorial-container.tsx
- src/constants/tutorial.constant.ts
- src/ui/common/button.common.tsx
> '로그인' 버튼을 '회원가입'으로 변경
> '회원가입' 및 '로그인' 폼에서 최대 너비 클래스 제거
> [Refactor/common] 로그인 및 회원가입 UI 수정

- src/app/(home)/components/home-header.tsx
- src/app/(layout)/header-desk.tsx
- src/app/(layout)/navigation.tsx
- src/app/layout.tsx
> 루트 레이아웃 고정
> 헤더 반응형 수정
> 네비게이션 반응형 수정
> [refactor/common]: 루트 레이아웃, 헤더, 네비게이션 반응형 CSS 수정

- src/app/(home)/components/home-calendar.tsx
- src/app/(home)/components/home-date.tsx
- src/app/(home)/components/home-friend.tsx
- src/app/(home)/components/home-music.tsx
- src/app/(home)/components/home-posting.tsx
- src/app/page.tsx
- src/ui/common/emotion-image.common.tsx
REF #107 
<br>
- strong 반영하기
- Link > a로 변경
- 홈 반응형 추가
- 캘린더 튀어나오는 현상 수정
<br>
<br>
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> [Style/Home] 홈 반응형 추가, 기타 작업 수정 #107

- src/app/friends/request/page.tsx
- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/list-card.tsx
- src/app/sign-in/_components/sign-in-form.tsx
- src/ui/common/mypage-emotion-graph.tsx
- tailwind.config.ts
> [Refactor/List] 디자인 수정 및 config 파일 수정

- package.json
- pnpm-lock.yaml
- src/app/(home)/components/home-friend.tsx
- src/app/(layout)/navigation.tsx
- src/app/friends/request/page.tsx
- src/app/list/_components/list-card-container.tsx
- src/hooks/zustand/list-tab-store.ts
- src/ui/common/tab.tsx
> 탭 컴포넌트
1. 사용 컴포넌트에서 아래와같이 tabs와 state를 선언해줍니다.
```  const tabs = [
{ id: "firstTab", label: "받은 요청" },
{ id: "secondTab", label: "보낸 요청" },
];
const [activeTab, setActiveTab] = useState(tabs[0].id);
```
2. Tab 컴포넌트에 props로 `tabs, activeTab, setActiveTab` 을 보내줍니다.
```
<Tab tabs={tabs} activeTab={activeTab} setActiveTab={setActiveTab} />
```
<br>
> [Feature] 탭 컴포넌트

- src/app/(home)/components/home-header.tsx
- src/app/(layout)/header-desk.tsx
- src/app/layout.tsx
- src/app/my-page/components/mypage-menu-item.tsx
- src/app/my-page/components/mypage-menu-list.tsx
- src/app/my-page/components/mypage-profile.tsx
- src/app/my-page/page.tsx
- src/ui/common/mypage-emotion-graph.tsx
> 마이페이지 반응형
<br>
<br>
> header 부분은 선영님과 상의 후 브라우저 버전 다시 수정하겠습니다.
> 전체적으로 다시 한 번 상의가 필요합니다.
> [Style/my] 마이페이지 반응형 CSS 1차 완료

- src/app/music/_components/emotion-select.tsx
- src/app/music/_components/playlist-content.tsx
- src/app/music/_components/playlist-tab-container.tsx
- src/app/music/page.tsx
> 뮤직페이지 반응형
<br>
<br>
> 스크롤 고정 시 문제 많습니다.
> 전체적으로 다시 한 번 상의가 필요합니다.
> [Style/music] 뮤직페이지 반응형 CSS 1차 완료

- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/list-card.tsx
- src/types/components-props.type.ts
- src/ui/common/alert.common.tsx
- src/ui/common/button.common.tsx
- src/ui/common/emotion-graph.common.tsx
- src/ui/common/mypage-emotion-graph.tsx
> 버튼 컴포넌트 추가 (backgroundColor='sub' 넣어주시면 연두, 넣지 않으면 기본 메인컬러 적용됨)
<br>
> [Feature] 버튼 컴포넌트, alert 컴포넌트

- src/app/list/_components/list-card.tsx
- src/ui/common/emotion-graph.common.tsx
- src/ui/common/mypage-emotion-graph.tsx
> 반응형 추가
> props 변경 (마이페이지에서도 사용 가능하게)
<br>
> [Refactor] 그래프 컴포넌트 반응형 추가

- src/app/(home)/components/home-header.tsx
- src/app/posting/[id]/page.tsx
- src/app/posting/_components/posting-button.tsx
- src/app/posting/_components/posting-form.tsx
- src/app/posting/page.tsx
- src/constants/form-message.constant.ts
> [Style/post]: PostingPage 반응형 CSS 수정

- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/list-card.tsx
- src/ui/common/tab.common.tsx
- #108 
<br>
> 반응형 구현
<br>
https://github.com/fourkie/fourkie/pull/161
> [Refactor/List] 반응형 구현

- src/app/(layout)/header-desk.tsx
- src/app/sign-in/_components/sign-in-form.tsx
- src/app/sign-in/page.tsx
- src/app/sign-up/_components/sign-up-form.tsx
- src/app/sign-up/page.tsx
- src/ui/common/input.common.tsx
> [Style/sign]: 로그인 및 회원가입 페이지 반응형 수정

- src/app/list/_components/list-card.tsx
- src/constants/alert-message.ts
- src/ui/common/alert.common.tsx
- src/ui/common/button.common.tsx
> [Feature] 버튼, 알림창 컴포넌트

- .vscode/settings.json
- src/app/(home)/components/home-header.tsx
- src/app/friends/page.tsx
- src/app/list/page.tsx
- src/app/music/page.tsx
- src/app/my-page/page.tsx
- src/app/notice/page.tsx
- src/app/posting/_components/posting-form.tsx
- src/app/smookie-makers/page.tsx
- src/app/terms/page.tsx
- src/middleware.ts
- src/services/middleware.ts
close #155 
<br>
- Protected Route 설정
- MiddleWare 설정
<br>
<br>
>
- 저희 발표날 둘다 풀어야합니다!
> [Feature/Sign] Protected Route, MiddleWare 설정

- src/app/(layout)/header-desk.tsx
- src/app/(layout)/main-content-container.tsx
- src/app/globals.css
- src/app/layout.tsx
- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/list-card.tsx
- src/app/sign-in/_components/sign-in-form.tsx
- src/app/sign-up/_components/sign-up-form.tsx
- src/ui/common/emotion-graph.common.tsx
- src/ui/common/input.common.tsx
- src/ui/common/tab.common.tsx
- tailwind.config.ts
- #108 
<br>
> 루트 레이아웃 css 수정
> 리스트 페이지 css 수정
> 그래프 컴포넌트 css 수정
> 버튼 컴포넌트 css 및 기능 수정
<br>
> [Feature] 레이아웃 및 리스트 페이지 css

- src/app/(home)/components/home-calendar.tsx
- src/app/(home)/components/home-friend.tsx
- src/app/(home)/components/home-header.tsx
- src/app/(home)/components/home-music.tsx
- src/app/(home)/components/home-posting.tsx
- src/app/friends/page.tsx
- src/app/page.tsx
- src/app/smookie-makers/page.tsx
REF #107 
<br>
- 현식님이 바꾼거 되돌렸습니다 (뒤로가기)
- 홈 반응형 진행중입니다.
<br>
<br>
> [Style/home] 홈 반응형 및 자잘한 수정 #107

- src/app/(layout)/header-desk.tsx
- src/app/(layout)/main-content-container.tsx
- src/constants/emotion.constant.ts
- src/ui/common/cookie-alert.common.tsx
> 레이아웃 하단 패딩 수정
> 공통 컴포넌트 (데이터 없을 때 컴포넌트) 수정 (cookie-alert)
> [Feature] 레이아웃 수정

- src/app/music/_components/playlist-content.tsx
- src/app/music/page.tsx
- src/ui/common/loading-cookie.common.tsx
- #174
<br>
> 공통 로딩 컴포넌트 추가
> 애니메이션 추가
> [Feature/loading] 공통 로딩 컴포넌트 #174

- src/hooks/polling/use-polling-query.ts
- src/hooks/queries/use-get-my-friends-query.ts
- src/hooks/queries/use-get-received-requests-query.ts
- src/services/friend-request-service.ts
> [Feature] Polling 실시간

- src/app/(home)/components/home-calendar.tsx
- src/app/(home)/components/home-music.tsx
- src/app/(layout)/header-mobile.tsx
- src/app/(layout)/navigation.tsx
- src/app/tutorial/_components/tutorial-description.tsx
Ref #107 
<br>
- 네비바 높이 줄이기/ 작성 버튼 키우기 / 폰트 사이즈 바꾸기 / 네비 리펙토링
- 헤더 색상 바꾸기 / 헤더 strong으로 바꾸기
- 튜토리얼 뒤로가기 오른쪽으로 옮기기
- 홈 뮤직 default 값 주기
> [Style/home] 헤더 네비 홈 css 피드백 반영 및 네비 리펙토링 #107

- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/list-card.tsx
- src/constants/alert-message.ts
- src/ui/common/alert.common.tsx
- src/ui/common/button.common.tsx
- src/ui/common/emotion-graph.common.tsx
- src/ui/common/tab.common.tsx
- #108 
<br>
> 애니메이션 추가
> 버튼 컴포넌트 디자인 수정
> 알림 수정
> [Feature/list] 애니메이션 추가 및 컴포넌트 디자인 수정

- package.json
- pnpm-lock.yaml
- src/app/friends/components/friend-list.tsx
- src/app/friends/components/friend-request-button.tsx
- src/app/friends/components/friend-request-popup.tsx
- src/app/friends/components/friend-search-input.tsx
- src/app/friends/page.tsx
- src/app/friends/request/components/friend-request-received-friend-list.tsx
- src/app/friends/request/components/friend-request-sent-friend-list.tsx
- src/app/friends/request/page.tsx
- src/app/my-page/components/mypage-profile.tsx
- src/app/my-page/page.tsx
- src/app/notice/page.tsx
- src/app/smookie-makers/page.tsx
- src/app/terms/page.tsx
- src/constants/toast-message.constant.ts
- src/hooks/mutations/use-delete-friend-mutation.ts
- #109 
<br>
<br>
<br>
> 자잘한 CSS 코드는 사진 첨부 안했습니다!
> [Refactor/userpage] 친구 요청이 있는 사용자에게 요청 시 수락 루트로 로직 변경 / CSS 전반적인 수정 / 친구 삭제 토스트 추가

- src/app/error.tsx
- src/app/list/page.tsx
- src/app/loading.tsx
- 업듬
<br>
> 에러 페이지 제작
> 로딩 페이지 제작
<br>
> [Feature/Error] 에러 페이지, 로딩 페이지

- src/app/list/_components/conetent.tsx
- src/app/list/_components/list-card.tsx
- src/hooks/is-mobile/use-is-mobile.ts
- #108 
- 
<br>
> 반응형 디자인 작업
<br>
> [Feature/List] 반응형 디자인 및 애니메이션

- src/app/(layout)/header-mobile.tsx
- src/app/(layout)/navigation.tsx
- src/app/posting/[id]/page.tsx
- src/app/posting/_components/posting-button.tsx
- src/app/posting/_components/posting-emotion-modal-button.tsx
- src/app/posting/_components/posting-emotion-modal-loading.tsx
- src/app/posting/_components/posting-emotion-modal-slice.tsx
- src/app/posting/_components/posting-emotion-modal.tsx
- src/app/posting/_components/posting-form.tsx
- src/app/posting/page.tsx
- src/hooks/zustand/posting-store.ts
- src/types/zustand.type.ts
- #117 
<br>
- 포스팅 페이지에서 뒤로가기 클릭 시 알림 창 띄움
- 포스팅 수정 완료 시 List 페이지로 이동
- 포스팅 쪽 aria 추가
- bold를 string으로 변경
<br>
<br>
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> [Refactor/Posting] 포스팅 페이지 뒤로가기 알림 창 #117

- src/app/(home)/components/home-calendar.tsx
- src/app/(home)/components/home-music.tsx
- src/app/(home)/components/home-posting.tsx
- src/app/(home)/components/home-stack.tsx
- src/app/(layout)/header-desk.tsx
- src/app/(layout)/header-mobile.tsx
- src/app/(layout)/navigation.tsx
Ref #107 
<br>
- 홈 스르륵 애니메이션, 리펙토링 및 호버
> [Style/home] 홈 스르륵 애니메이션, 리펙토링 및 호버 #107

- src/ui/common/footer.common.tsx
- src/ui/svg-icon/github.icon.tsx
- src/ui/svg-icon/google.icon.tsx
- src/ui/svg-icon/spotify.icon.tsx
- #174
<br>
> Footer 디자인 수정
<br>
<br>
> [Feature/footer] : Footer 컴포넌트 CSS 수정 #174

- src/app/(home)/components/home-calendar.tsx
- src/app/(home)/components/home-friend.tsx
- src/app/(home)/components/home-loading.tsx
- src/app/(home)/components/home-music.tsx
- src/app/(layout)/header-desk.tsx
- src/app/loading.tsx
- src/app/page.tsx
ref #107 
<br>
-  애니메이션
-  호버
-  홈 커스텀 로딩
> [Style/home] 애니메이션, 호버, 홈 커스텀 로딩 #107

- src/app/music/_components/playlist-card.tsx
- src/app/music/_components/playlist-content.tsx
> [Refactor/music]: Music 페이지 CSS 수정 #135

- src/app/(layout)/header-desk.tsx
- src/app/(layout)/navigation.tsx
- src/app/list/_components/list-card-container.tsx
- src/app/list/_components/my-posts-list.tsx
- src/hooks/queries/use-get-friend-posts-query.ts
- src/hooks/queries/use-infinite-user-posts-by-month-query.ts
- src/hooks/zustand/post-date-store.ts
- #108 
<br>
> 무한스크롤 구현 엉엉
> 코드 너무 지저분해져서 무한스크롤부분은 따로 컴포넌트로 빼서 리팩토링 하겠습니다 (언젠간)
<br>
> [Feature/List] 무한스크롤

- src/app/page.tsx
- src/app/sign-in/page.tsx
- #125 
<br>
- 튜토리얼 처음나오는 페이지 home -> 로그인 페이지로 로직 이동
<br>
<br>
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?
> [Refactor:Tutorial] 튜토리얼 확인 로직을 SignIn 페이지로 이동

- src/app/music/_components/playlist-content.tsx
- src/app/music/page.tsx
- src/hooks/is-mobile/use-is-mobile.ts
- src/ui/common/tab.common.tsx
> [Feature/music] 디자인 수정

- src/app/tutorial/_components/tutorial-description.tsx
> 목업 이미지 넓이 추가 및 좌우 패딩 제거
> 좌우 슬라이드 추가
> 노션 137회 UI 개선 확인 후 css 재조정 필요합니다.
> [Refactor]: 일부 튜토리얼 css 수정
